### PR TITLE
Look for specific file in hide/show keys

### PR DESCRIPTION
**Pull request by boredz**
I've installed the [gulp-control](https://atom.io/packages/gulp-control) package and added it to my toolbar, but I can make it visible only in JS files.
It would be nice if we could write in the `hide`, `show`, `disable` and `enable` keys a string that can look for a specific file (eg: `./**/gulpfile.[js|coffee]`) in the actual project folder :smile:

### CODE REVIEW

**Comment by boredz** [comment]
I tried to add this feature by myself, it's my first try to edit an Atom package so if you don't like how I made it just ignore this pull request :smile: 

In the first commit I replaced `grammar.includes '!'` because this function returns true even if you write something like `Mark!Down`. I don't think that this is the way you want it to work.

In the second commit I added the feature using [Glob](https://github.com/isaacs/node-glob). 
Oh, if you have two open projects it will show the button only if the file that you're looking for is in the current tab's project folder, otherwise it will be hidden.

In the third commit I changed a little the readme file and explained the new feature.

**Comment by cakecatz** [comment]
> In the second commit I added the feature using Glob.

If there are many files in project folder, `glob` process become slow.
Actually, I opened `~/.atom` and crashed Atom.

So I think we should use [minimatch](https://github.com/isaacs/minimatch) instead to `glob`.

And this is good feature for `flex-tool-bar` :smile: 
Thanks for PR!

**Comment by boredz** [comment]
> You can use `atom.workspace.getActiveTextEditor().getPath()` to get active file path :)

That's a better way to do it?
> If there are many files in project folder, glob process become slow.
> Actually, I opened `~/.atom` and crashed Atom.

I used the `sync` function, actually `.atom` has a lot of `node_modules` directories. It would be better to use the `async` function.
I can use the `ignore` key (minimatch doesn't have this) in `options` to ignore the `node_modules` directory (and maybe others, like the one that bower uses) and enable `cache`.
I can also make `show` an object, it'll contain something like:
```coffeescript
show: {
  path: './**/gulpfile.js'
  ignore: ['./**/node_modules', './**/bower_scripts']
}
```
Or maybe we should just warn the users to not use the double-star character and try to match only files with a known path (e.g. `./.git/HEAD` not `./**/HEAD`).

**Comment by cakecatz** [comment]
> That's a better way to do it?

I think so.


> I used the sync function, actually .atom has a lot of node_modules directories. It would be better to use the async function.
> I can use the ignore key (minimatch doesn't have this) in options to ignore the node_modules directory (and maybe others, like the one that bower uses) and enable cache.
> I can also make show an object, it'll contain something like:

`glob` does file searching and `minimatch` does filename matching.
In the case of `glob`, If you have too many files that don't want ignore, it affect to performance. 
But `minimatch` don't affect to performance.

**Comment by boredz** [comment]
> But minimatch don't affect to performance.

Yep, but minimatch needs a fileList (array of strings, I think) to perform a search, it doesn't get it on its own. I have to use a module like [directory-tree](https://github.com/mihneadb/node-directory-tree) (it's faster than glob, ~500ms/search in `~/.atom`, but it just gets the tree).
I can also spawn the `tree` command and parse it, but maybe it would be better to create a module for this.


> Actually, I opened ~/.atom and crashed Atom.

Just to know, how many packages do you have? I made a test with Glob, it takes ~800ms to search for `~/.atom/**/*` (I know that's too much, a delay of 1s when you change the tab is not good).

**Comment by cakecatz** [comment]
> Yep, but minimatch needs a fileList (array of strings, I think) to perform a search,

`minimatch` doesn't needs a fileList in this case.

```coffeescript
currentFile = atom.workspace.getActiveTextEditor().getPath()
minimatch currentFile, pattern, { matchBase: true } // return true or false
```
This code do regex match. So file amount is not related.



> Just to know, how many packages do you have? I made a test with Glob, it takes ~800ms to search for ~/.atom/**/* (I know that's too much, a delay of 1s when you change the tab is not good).

I tried test with `glob`.

```javascript
console.time('glob');
glob(os.homedir() + '/.atom/**/*.js', {}, () => {
  console.timeEnd('glob');
});
```
```bash
glob: 9550.450ms
```
screen shot 2015-11-09 at 4 05 27 am

**Comment by boredz** [comment]
>```coffeescript
minimatch currentFile, pattern, { matchBase: true } // return true or false
```

Does it search the `pattern` in the file's project folder or just match the regex on the file path? (e.g. if the pattern is `./**/gulpfile.js` and `currentFile = '~/.proj/gulpfile.js'` returns `true`, if `currentFile = '~/.proj/gulp.js'` returns `false`).
This feature should return `true` if the pattern is matched in the project folder and not only in the active file's path (maybe that's a different feature that may be useful for someone).

**Comment by cakecatz** [comment]
> Does it search the pattern in the file's project folder or just match the regex on the file path? (e.g. if the pattern is ./**/gulpfile.js and currentFile = '~/.proj/gulpfile.js' returns true, if currentFile = '~/.proj/gulp.js' returns false).

It matches regex on the file path only.

> (maybe that's a different feature that may be useful for someone).

What do you mean by this?

**Comment by boredz** [comment]
> What do you mean by this?

I want to show a button only if there is a specific file in my project folder (e.g. I want to show the `gulp-control` button if there's a `gulpfile.js` file in my project folder, even if my active tab is displaying a different file).
From what I understood you want to show the button only if the file you're editing is a specific file.

I think that we're talking about two different features :laughing:

**Comment by cakecatz** [comment]
Oh, I get it! :astonished:

**Comment by boredz** [comment]
I know, I'm going to write a little script based on the `tree` command.

Anyway, I think that the size of your `.atom` folder is unusual. I don't think that a lot of people work with folders that contain such a big amount of data. 

IMHO your folder should be considered as an *extreme test* :stuck_out_tongue_winking_eye:

**Comment by boredz** [comment]
I'm alive (yay).

So, with this commit I used my module ([tree-match-sync](https://github.com/boredz/tree-match-sync)) and it should be faster, but some things changed.

Show a button only if the file you're editing has a specific name:
```coffeescript
{
  type: 'button'
  icon: 'coffee'
  iconset: 'ion'
  show: 'myFile.coffee'
}
```
You can negate it (`!myFile.coffee`), so it'll be shown in any other file that isn't `myFile.coffee`.

Show a button if a file is matched in the project folder:
```coffeescript
{
  type: 'button'
  icon: 'coffee'
  iconset: 'ion'
  show: {
    pattern: 'gulpfile.js'
    options: {
      maxDepth: 2
    }
  }
}
```
`pattern` and `options` are the same used in my [module](https://github.com/boredz/tree-match-sync#usage), follow its *rules*.
I recommend to always set the `maxDepth` field.


Tell me what do you think now and I'll change also the readme :relieved:

**Comment by cakecatz** [comment]
> Show a button only if the file you're editing has a specific name:

It looks good to me :ok_woman: 

> Show a button if a file is matched in the project folder:

Maybe `tree` command is not installed on OS X by default.
Could you add support for darwin platform?

**Comment by boredz** [comment]
I forget to say that you have to [install](https://github.com/boredz/tree-match-sync#installation) it with `brew`, it's not installed by default even on some Linux distributions.

I don't know how it works on OS X, but if it's a standalone executable file (like [the one for windows](https://github.com/boredz/tree-match-sync/tree/master/bin)) I can include it in the `bin` folder (maybe I can do this also for Linux) :grin:

**Comment by boredz** [comment]
There was a bug with `show`'s object on untitled tabs, I fixed it :yum:

**Comment by cakecatz** [comment]
Could you add `notification` of missing `tree`?

After that I'll merge this PR.

**Comment by boredz** [comment]
Is there an Atom function that let you create and show notifications?

**Comment by boredz** [comment]
Can you tell me if `which` command is pre-installed on OS X?

**Comment by boredz** [comment]
Done :grin:

**Comment by cakecatz** [comment]
OK :+1:

**Comment by cakecatz** [comment]
Thanks @boredz!

**Pull request merged**
