### PR TITLE
add support for browser-plus

### PR DESCRIPTION
**Pull request by flexzuu**
Hey i wanted to use browser plus instead of a default browser. 
Hope you like the changes. This is my first pull request so please tell me if did something wrong!
I added the support by adding a options checkbox.

### CODE REVIEW

**Comment by cakecatz** [comment]
@flexzuu I think need checking `browser-plus` has installed.
Thanks for PR :)

**Comment by flexzuu** [comment]
I did not know that was possible but it sounds logical. If you hint me somewhere a check like that is used i can implement it.

**Comment by cakecatz** [comment]
@flexzuu You can use `atom.packages.isPackageActive()` :smile: 
https://atom.io/docs/api/v1.0.19/PackageManager#instance-isPackageActive

**Comment by flexzuu** [comment]
Hey i am trying to check, to only show the checkbox if the user has browser-plus install but i cant get it to work because i dont get the config to load dynamicly. in about 2 h i will commit a change to my repo that introduces an additonal check. that if the user has the box checkt but not install browers-plus will still open in the brower and do get an error.

**Comment by cakecatz** [comment]
@flexzuu 



> Hey i am trying to check, to only show the checkbox if the user has browser-plus install but i cant get it to work because i dont get the config to load dynamicly.

It's possible, but hassle.
So I think it is good to change config key.(e.g. `useBrowserPlusWhenItIsActive`)



> that if the user has the box checkt but not install browers-plus will still open in the brower and do get an error.

Sorry, I didn't get an error.
It can be reproduced?

Thanks.

**Comment by flexzuu** [comment]
Hey i have not implemented the error message jet but it should open in the default browser even if you select to use browser-plus and dont have it installted. I want to implement the warning as notification but have to lookup how to do it.

**Comment by cakecatz** [comment]
Oh, I get it.

**Comment by flexzuu** [comment]
I just added the notifaction i am not sure if the its right to use a warning or if we should better use an error. If you have suggestions for a better error text just tell me.

**Comment by cakecatz** [comment]
@flexzuu I think that's fine.
I'll merge this PR tonight if you have not any question.
Thanks!

**Comment by flexzuu** [comment]
Okay i thinks it is ready for merging.
Thank you.

**Comment by flexzuu** [comment]
Ohh crap i think we forgot to increase the version number.

**Pull request merged**
