### PR TITLE
Make sure that the tool-bar package is installed

### PR DESCRIPTION
**Pull request by jerone**
Same as https://github.com/suda/toolbar-main/pull/13.

Adds dependency to [atom-package-deps](https://www.npmjs.com/package/atom-package-deps).

### CODE REVIEW

**Comment by jerone** [comment]
We can probably remove the other `package-dependencies` property in the `package.json` and Tool Bar readme;

```
"package-dependencies": {
     "tool-bar": "^0.1.9"
   }
```

**Comment by cakecatz** [comment]
@jerone :ok_woman: 

> We can probably remove the other package-dependencies property in the package.json and Tool Bar readme;

yup!
That's used for [atom-package-dependencies](https://github.com/travs/atom-package-dependencies) and it has been removed now.

**Comment by jerone** [comment]
[**@cakecatz**](https://github.com/cakecatz) commented on [18 feb. 2016 17:15 CET](https://github.com/cakecatz/flex-toolbar/pull/55#issuecomment-185796726 "2016-02-18T16:15:48Z - Replied by Github Comment Enhancer"):
> That's used for [atom-package-dependencies](https://github.com/travs/atom-package-dependencies) and it has been already removed.

Yeah, for Main Tool Bar I [did](https://discuss.atom.io/t/depending-on-other-packages/2360/30) some research and atom-package-deps was better updated and provides a nice UI when downloading dependencies.

**Comment by jerone** [comment]
Hmm just discovered a bug where the activation code won't execute when the package is installed.

**Comment by jerone** [comment]
Everything is working again. Did came across https://github.com/cakecatz/flex-toolbar/issues/29 when testing.

**Comment by cakecatz** [comment]
@jerone OK!

**Pull request merged**
